import React, { useState, useEffect } from 'react';
import { DownloadOptions, CommandBuildResult } from '../../../shared/types';
import {
  Terminal,
  Copy,
  Check,
  Download,
  Share2,
  FileCode,
  Sliders,
  Sparkles,
  Info
} from 'lucide-react';

interface CommandBuilderViewProps {
  initialOptions?: DownloadOptions;
  defaultOutputDir: string;
  onSendToDownload: (options: DownloadOptions) => void;
}

export const CommandBuilderView: React.FC<CommandBuilderViewProps> = ({
  initialOptions,
  defaultOutputDir,
  onSendToDownload
}) => {
  const [url, setUrl] = useState(initialOptions?.url || 'https://www.youtube.com/watch?v=dQw4w9WgXcQ');
  const [formatSelection, setFormatSelection] = useState(initialOptions?.formatSelection || 'bv*+ba/b');
  const [audioOnly, setAudioOnly] = useState(initialOptions?.audioOnly || false);
  const [audioFormat, setAudioFormat] = useState(initialOptions?.audioFormat || 'mp3');
  const [audioQuality, setAudioQuality] = useState(initialOptions?.audioQuality || '0');
  const [mergeOutputFormat, setMergeOutputFormat] = useState(initialOptions?.mergeOutputFormat || 'mp4');
  const [embedThumbnail, setEmbedThumbnail] = useState(initialOptions?.embedThumbnail ?? true);
  const [embedMetadata, setEmbedMetadata] = useState(initialOptions?.embedMetadata ?? true);
  const [embedSubtitles, setEmbedSubtitles] = useState(initialOptions?.embedSubtitles ?? false);
  const [writeSubtitles, setWriteSubtitles] = useState(initialOptions?.writeSubtitles ?? false);
  const [subLanguages, setSubLanguages] = useState(initialOptions?.subLanguages || 'en,all');
  const [writeDescription, setWriteDescription] = useState(initialOptions?.writeDescription ?? false);
  const [writeInfoJson, setWriteInfoJson] = useState(initialOptions?.writeInfoJson ?? false);
  const [rateLimit, setRateLimit] = useState(initialOptions?.rateLimit || '');
  const [proxy, setProxy] = useState(initialOptions?.proxy || '');
  const [cookiesBrowser, setCookiesBrowser] = useState(initialOptions?.cookiesBrowser || '');
  const [rawArgs, setRawArgs] = useState('');

  const [buildResult, setBuildResult] = useState<CommandBuildResult>({
    command: '',
    args: [],
    explanations: []
  });
  const [copied, setCopied] = useState(false);

  // Compute live command
  useEffect(() => {
    const customArgsList = rawArgs
      .split(' ')
      .map((s) => s.trim())
      .filter((s) => s.length > 0);

    const options: DownloadOptions = {
      url: url || '<URL>',
      formatSelection: audioOnly ? undefined : formatSelection,
      audioOnly,
      audioFormat: audioOnly ? (audioFormat as any) : undefined,
      audioQuality: audioOnly ? audioQuality : undefined,
      mergeOutputFormat: !audioOnly ? mergeOutputFormat : undefined,
      embedThumbnail,
      embedMetadata,
      embedSubtitles,
      writeSubtitles,
      subLanguages: embedSubtitles || writeSubtitles ? subLanguages : undefined,
      writeDescription,
      writeInfoJson,
      rateLimit: rateLimit.trim() ? rateLimit.trim() : undefined,
      proxy: proxy.trim() ? proxy.trim() : undefined,
      cookiesBrowser: cookiesBrowser.trim() ? cookiesBrowser.trim() : undefined,
      customArgs: customArgsList.length > 0 ? customArgsList : undefined
    };

    window.electronAPI.buildCommand(options).then((res) => {
      setBuildResult(res);
    });
  }, [
    url,
    formatSelection,
    audioOnly,
    audioFormat,
    audioQuality,
    mergeOutputFormat,
    embedThumbnail,
    embedMetadata,
    embedSubtitles,
    writeSubtitles,
    subLanguages,
    writeDescription,
    writeInfoJson,
    rateLimit,
    proxy,
    cookiesBrowser,
    rawArgs
  ]);

  const handleCopy = () => {
    navigator.clipboard.writeText(buildResult.command);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportScript = (ext: 'bat' | 'sh' | 'ps1') => {
    let scriptContent = '';
    if (ext === 'bat') {
      scriptContent = `@echo off\nREM Generated by yt-dlp Professional Desktop GUI\n${buildResult.command}\npause\n`;
    } else if (ext === 'ps1') {
      scriptContent = `# Generated by yt-dlp Professional Desktop GUI\n${buildResult.command}\n`;
    } else {
      scriptContent = `#!/usr/bin/env bash\n# Generated by yt-dlp Professional Desktop GUI\n${buildResult.command}\n`;
    }

    const blob = new Blob([scriptContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `download_script.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleQueueFromBuilder = () => {
    const customArgsList = rawArgs
      .split(' ')
      .map((s) => s.trim())
      .filter((s) => s.length > 0);

    onSendToDownload({
      url,
      formatSelection: audioOnly ? undefined : formatSelection,
      audioOnly,
      audioFormat: audioOnly ? (audioFormat as any) : undefined,
      audioQuality: audioOnly ? audioQuality : undefined,
      mergeOutputFormat: !audioOnly ? mergeOutputFormat : undefined,
      embedThumbnail,
      embedMetadata,
      embedSubtitles,
      writeSubtitles,
      subLanguages: embedSubtitles || writeSubtitles ? subLanguages : undefined,
      writeDescription,
      writeInfoJson,
      rateLimit: rateLimit.trim() ? rateLimit.trim() : undefined,
      proxy: proxy.trim() ? proxy.trim() : undefined,
      cookiesBrowser: cookiesBrowser.trim() ? cookiesBrowser.trim() : undefined,
      customArgs: customArgsList.length > 0 ? customArgsList : undefined
    });
  };

  return (
    <div className="view-container">
      {/* Live Generated Command Bar */}
      <div className="card">
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontWeight: 600, fontSize: 15, color: 'var(--text-primary)' }}>
            <Terminal size={18} color="var(--accent-primary-bright)" />
            Generated yt-dlp CLI Command
          </div>

          <div style={{ display: 'flex', gap: 8 }}>
            <button onClick={handleCopy} className="btn-secondary" style={{ fontSize: 12, padding: '6px 14px' }}>
              {copied ? <Check size={14} color="var(--accent-success)" /> : <Copy size={14} />}
              {copied ? 'Copied' : 'Copy'}
            </button>
            <button onClick={() => handleExportScript('bat')} className="btn-secondary" style={{ fontSize: 12, padding: '6px 10px' }}>
              .bat
            </button>
            <button onClick={() => handleExportScript('ps1')} className="btn-secondary" style={{ fontSize: 12, padding: '6px 10px' }}>
              .ps1
            </button>
            <button onClick={() => handleExportScript('sh')} className="btn-secondary" style={{ fontSize: 12, padding: '6px 10px' }}>
              .sh
            </button>
            <button onClick={handleQueueFromBuilder} className="btn-primary" style={{ fontSize: 13, padding: '6px 16px' }}>
              <Download size={14} /> Queue Job
            </button>
          </div>
        </div>

        <div className="code-block" style={{ fontSize: 13, minHeight: 48, lineHeight: 1.6 }}>
          {buildResult.command}
        </div>
      </div>

      {/* Interactive Options Panels */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(360px, 1fr))', gap: 16 }}>
        {/* Stream & Media Options */}
        <div className="card">
          <h3 style={{ fontSize: 15, fontWeight: 600, marginBottom: 14, display: 'flex', alignItems: 'center', gap: 8 }}>
            <Sliders size={16} color="var(--accent-primary)" />
            Stream & Container Configuration
          </h3>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
            <div>
              <label style={{ display: 'block', fontSize: 12, fontWeight: 600, marginBottom: 4 }}>Target URL</label>
              <input
                type="text"
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                style={{ width: '100%' }}
              />
            </div>

            <div style={{ display: 'flex', gap: 16 }}>
              <label style={{ display: 'flex', alignItems: 'center', gap: 6, cursor: 'pointer' }}>
                <input
                  type="checkbox"
                  checked={audioOnly}
                  onChange={(e) => setAudioOnly(e.target.checked)}
                />
                Audio Only Mode (-x)
              </label>
            </div>

            {audioOnly ? (
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
                <div>
                  <label style={{ display: 'block', fontSize: 12, fontWeight: 600, marginBottom: 4 }}>Audio Format</label>
                  <select
                    value={audioFormat}
                    onChange={(e) => setAudioFormat(e.target.value as any)}
                    style={{ width: '100%' }}
                  >
                    <option value="mp3">MP3</option>
                    <option value="m4a">M4A / AAC</option>
                    <option value="opus">Opus</option>
                    <option value="flac">FLAC (Lossless)</option>
                    <option value="wav">WAV</option>
                  </select>
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: 12, fontWeight: 600, marginBottom: 4 }}>Audio Quality</label>
                  <select
                    value={audioQuality}
                    onChange={(e) => setAudioQuality(e.target.value)}
                    style={{ width: '100%' }}
                  >
                    <option value="0">0 (Best VBR / 320k)</option>
                    <option value="2">2 (High ~190k)</option>
                    <option value="5">5 (Medium ~130k)</option>
                  </select>
                </div>
              </div>
            ) : (
              <>
                <div>
                  <label style={{ display: 'block', fontSize: 12, fontWeight: 600, marginBottom: 4 }}>Format Expression (-f)</label>
                  <input
                    type="text"
                    value={formatSelection}
                    onChange={(e) => setFormatSelection(e.target.value)}
                    style={{ width: '100%', fontFamily: 'var(--font-mono)' }}
                  />
                </div>

                <div>
                  <label style={{ display: 'block', fontSize: 12, fontWeight: 600, marginBottom: 4 }}>Merge Output Format (--merge-output-format)</label>
                  <select
                    value={mergeOutputFormat}
                    onChange={(e) => setMergeOutputFormat(e.target.value as any)}
                    style={{ width: '100%' }}
                  >
                    <option value="mp4">mp4</option>
                    <option value="mkv">mkv</option>
                    <option value="webm">webm</option>
                  </select>
                </div>
              </>
            )}
          </div>
        </div>

        {/* Post-Processing, Subtitles, Network */}
        <div className="card">
          <h3 style={{ fontSize: 15, fontWeight: 600, marginBottom: 14, display: 'flex', alignItems: 'center', gap: 8 }}>
            <Sparkles size={16} color="var(--accent-purple)" />
            Post-Processing & Network
          </h3>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
              <label style={{ display: 'flex', alignItems: 'center', gap: 6, cursor: 'pointer', fontSize: 13 }}>
                <input
                  type="checkbox"
                  checked={embedThumbnail}
                  onChange={(e) => setEmbedThumbnail(e.target.checked)}
                />
                Embed Thumbnail
              </label>

              <label style={{ display: 'flex', alignItems: 'center', gap: 6, cursor: 'pointer', fontSize: 13 }}>
                <input
                  type="checkbox"
                  checked={embedMetadata}
                  onChange={(e) => setEmbedMetadata(e.target.checked)}
                />
                Embed Metadata
              </label>

              <label style={{ display: 'flex', alignItems: 'center', gap: 6, cursor: 'pointer', fontSize: 13 }}>
                <input
                  type="checkbox"
                  checked={embedSubtitles}
                  onChange={(e) => setEmbedSubtitles(e.target.checked)}
                />
                Embed Subtitles
              </label>

              <label style={{ display: 'flex', alignItems: 'center', gap: 6, cursor: 'pointer', fontSize: 13 }}>
                <input
                  type="checkbox"
                  checked={writeInfoJson}
                  onChange={(e) => setWriteInfoJson(e.target.checked)}
                />
                Write .info.json
              </label>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
              <div>
                <label style={{ display: 'block', fontSize: 12, fontWeight: 600, marginBottom: 4 }}>Rate Limit (--limit-rate)</label>
                <input
                  type="text"
                  placeholder="e.g. 5M, 500K"
                  value={rateLimit}
                  onChange={(e) => setRateLimit(e.target.value)}
                  style={{ width: '100%' }}
                />
              </div>

              <div>
                <label style={{ display: 'block', fontSize: 12, fontWeight: 600, marginBottom: 4 }}>Proxy (--proxy)</label>
                <input
                  type="text"
                  placeholder="socks5://127.0.0.1:1080"
                  value={proxy}
                  onChange={(e) => setProxy(e.target.value)}
                  style={{ width: '100%' }}
                />
              </div>
            </div>

            <div>
              <label style={{ display: 'block', fontSize: 12, fontWeight: 600, marginBottom: 4 }}>
                Expert Raw Arguments (Appended directly)
              </label>
              <input
                type="text"
                placeholder="e.g. --no-playlist --geo-bypass --sponsorblock-remove all"
                value={rawArgs}
                onChange={(e) => setRawArgs(e.target.value)}
                style={{ width: '100%', fontFamily: 'var(--font-mono)' }}
              />
            </div>
          </div>
        </div>
      </div>

      {/* Argument Breakdown Inspector */}
      <div className="card">
        <h3 style={{ fontSize: 15, fontWeight: 600, marginBottom: 12, display: 'flex', alignItems: 'center', gap: 8 }}>
          <Info size={16} color="var(--accent-info)" />
          CLI Argument Breakdown ({buildResult.explanations.length} options active)
        </h3>

        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
            <thead>
              <tr style={{ backgroundColor: 'var(--bg-surface)', borderBottom: '1px solid var(--border-subtle)', textAlign: 'left' }}>
                <th style={{ padding: '10px 14px', width: 220 }}>Flag / Parameter</th>
                <th style={{ padding: '10px 14px', width: 220 }}>Argument Value</th>
                <th style={{ padding: '10px 14px' }}>yt-dlp Behavioral Description</th>
              </tr>
            </thead>
            <tbody>
              {buildResult.explanations.map((item, idx) => (
                <tr key={idx} style={{ borderBottom: '1px solid var(--border-subtle)' }}>
                  <td style={{ padding: '10px 14px', fontFamily: 'var(--font-mono)', fontWeight: 600, color: 'var(--accent-primary)' }}>
                    {item.flag}
                  </td>
                  <td style={{ padding: '10px 14px', fontFamily: 'var(--font-mono)', color: 'var(--text-secondary)' }}>
                    {item.value || '—'}
                  </td>
                  <td style={{ padding: '10px 14px', color: 'var(--text-primary)' }}>
                    {item.description}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
